version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j-db
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}  # Use values from the .env file
    ports:
      - 7474:7474   # HTTP port
      - 7687:7687   # Bolt port
    volumes:
      - neo4j-data:/data   # Persist database data
      - neo4j-logs:/logs   # Persist Neo4j logs
      - neo4j-import:/var/lib/neo4j/import   # Import files location
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
